### PR TITLE
Mod Compat Page

### PR DESCRIPTION
**Pull request by arthurbambou**

### CODE REVIEW

**Comment by BluCobalt** [comment]
Do you have screenshots

**Comment by arthurbambou** [comment]
image

**Review by BluCobalt — COMMENTED** [review]
I think it's cool but the table doesn't really fit with the rest of the page. Maybe it's too skinny?

**Comment by arthurbambou** [comment]
I'm not good with css and styling, I'll let someone else improve this part...

**Review by PseudoDistant — CHANGES_REQUESTED** [review]
master branch on GitHub works.

**Comment by PseudoDistant** [comment]
*Of AnTitanic

**Comment by arthurbambou** [comment]
Is it available anywhere to download as a jar?

**Comment by PseudoDistant** [comment]
> Is it available anywhere to download as a jar?

Unless GitHub Actions broke, I believe I set it up so you can just download artifacts.
Also `./gradlew build` isn't that hard...

**Comment by BluCobalt** [comment]
./gradlew build isn't hard, but is far from user friendly

**Comment by BluCobalt** [comment]
Do you have more screenshots

**Comment by arthurbambou** [comment]
image

**Review by BluCobalt — APPROVED** [review]
nice

**Pull request merged**
