### PR TITLE
Closes #16

### LINKED ISSUE #16: A mod should be removed from the site
See #15 and [TooManyItem's original page](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1272385-toomanyitems-the-inventory-editor-and-more-1-8).
TooManyItems does not adhere to the source project's license and should be removed from the site.

### PR DESCRIPTION
**Pull request by arthurbambou**

### CODE REVIEW

**Comment by HowardZHY** [comment]
remove it to avoid further arguments.
TMI LF is just a personal creation.

**Comment by NoobKiller1919** [comment]
It IS personal creation. Not yours, but Marglyph's.

**Comment by HowardZHY** [comment]
go and merge it. get rid of unpleasant debations

**Comment by arthurbambou** [comment]
Requires a review to merge

**Comment by arthurbambou** [comment]
Needs a second review then merge

**Review by BluCobalt — APPROVED** [review]

**Comment by BluCobalt** [comment]
I think if you changed the mod from redistributing tmi to consuming a jar of tmi (like optifabric) it would be ok

**Pull request merged**
