### PR TITLE
Update mods.js

### PR DESCRIPTION
**Pull request by arthurbambou**

### CODE REVIEW

**Review by BluCobalt — APPROVED** [review]
Looks cool

**Comment by HowardZHY** [comment]
Will 1.4-1.4.2 show on the list? I thonk only latest versions of each 1.x would be shown.

**Comment by arthurbambou** [comment]
Yeah they will

**Comment by arthurbambou** [comment]
One more approval please??

**Review by BoogieMonster1O1 — APPROVED** [review]

**Pull request merged**
